import "./globals.css";
import { Rubik } from "next/font/google";

import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Headless WordPress Example",
  description: "Generated by Franly the Manly",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
      {children}
      <header>
        <Navbar />
      </header>


        <footer>
       <Footer />
        </footer>
      </body>
    </html>
  );
}
